### ISSUE TITLE
Cannot install master branch VSBase.Extension in VS 2017

### ISSUE THREAD

**Issue by sharwell** [tunnelvisionlabs/vsbase#60]
The following exception is thrown if you try to install the **VSBase.Extension** extension in Visual Studio 2017.

```
1/27/2017 10:11:28 AM - Install Error : Microsoft.VisualStudio.ExtensionManager.NestedExtensionInstallException: The extension 'Tvl.VisualStudio.Commenter.F3FD3E6D-611C-4703-B160-0C425AAFBACF' nested within 'Tvl.VisualStudio.VSBase.26FF1250-16D3-498e-9C1D-B4FEB5EBF845' failed to install.
Object reference not set to an instance of an object. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.VisualStudio.ExtensionManager.InstallableExtensionImpl.RefreshExtractedPackageStream(IInstalledExtension parentExtension, IExtensionReference reference)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.InstallNestedExtensions(InstallableExtensionImpl parentExtension, IInstalledExtension installedParentExtension, ZipPackage parentVSIX, InstallFlags installFlags, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, AsyncOperation asyncOp, IProgress`1 progress)
   --- End of inner exception stack trace ---
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.InstallNestedExtensions(InstallableExtensionImpl parentExtension, IInstalledExtension installedParentExtension, ZipPackage parentVSIX, InstallFlags installFlags, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, AsyncOperation asyncOp, IProgress`1 progress)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.PerformLegacyInstall(InstallableExtensionImpl extension, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, IProgress`1 progress, InstallFlags installFlags, AsyncOperation asyncOp, Boolean isPackComponent, IInstalledExtension& newExtension)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.PerformSetupEngineInstall(InstallableExtensionImpl extension, Boolean installPerMachine, Boolean isPackComponent, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, IProgress`1 progress, InstallFlags installFlags, AsyncOperation asyncOp, IInstalledExtension& newExtension)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.InstallInternal(InstallableExtensionImpl extension, InstallFlags installFlags, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, AsyncOperation asyncOp, IProgress`1 progress)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.BeginInstall(IInstallableExtension installableExtension, InstallFlags installFlags, AsyncOperation asyncOp)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.InstallWorker(IInstallableExtension extension, InstallFlags installFlags, AsyncOperation asyncOp)
```

**Comment by sharwell** [comment]
This turned out to be a bug in Visual Studio 2017 RC. A later update to the IDE itself has now resolved it.
